### ISSUE TITLE
Add VkPhysicalDevicePortabilitySubsetFeaturesKHR:: shaderAtomicOperationLocal capability

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/Vulkan-Portability#49] opened 2022-03-01 03:00 UTC
Some CTS tests fail when using atomic operations on workgroup local variables.

This might be fixable with effort within the implementations.

In the meantime, these use cases can be disabled in CTS and reported as Not Supported, by adding a `VkPhysicalDevicePortabilitySubsetFeaturesKHR:: shaderAtomicOperationLocal` capability.

This affects 2 CTS tests:

```
dEQP-VK.compute.basic.image_atomic_op_local_size_1
dEQP-VK.compute.basic.image_atomic_op_local_size_8
validateComputeFunctionArguments, line 745: error 'Compute Function(main0): missing buffer binding at index 2 for _45_atomic[0].'
  Fail (Comparison failed for pixel 0)
```

**Comment by kvark** [comment] 2022-03-07 03:52
I think having atomics on workgroup memory is essential. Please reconsider putting an effort into fixing this instead of flagging off.

**Comment by cdavis5e** [comment] 2022-11-09 20:38
Based on that error message, it looks like the problem isn't workgroup variables *per se* as opposed to the fact that MoltenVK isn't passing down the buffer backing an image being accessed atomically. The names of those tests corroborate this.

**Comment by billhollings** [comment] 2022-11-10 19:50
> Based on that error message, it looks like the problem isn't workgroup variables _per se_ as opposed to the fact that MoltenVK isn't passing down the buffer backing an image being accessed atomically. The names of those tests corroborate this.

Ah. Good observation. I guess I didn't delve into the error message much before identifying this as an issue.

Should be fixable in MoltenVK then? That's good.

**Comment by cdavis5e** [comment] 2022-11-14 02:29
This has been fixed in MoltenVK.

**Closed as completed by cdavis5e** 2022-11-14 02:29 UTC
Labels: CTS
